import { TRACK_BASELINES } from 'config';
import { Cell, SpriteData } from 'sprites/model';

export const SAPPHIRE_CELLS_WIDTH = 35;

export const SAPPHIRE_CELLS_HEIGHT = 30;

export const SAPPHIRE_SPARKLE_DURATION = 100;

export const SAPPHIRE_SPARKLE_INTERVAL = 300;

export const SAPPHIRE_CELLS: Cell[] = [
  new Cell(185, 138, SAPPHIRE_CELLS_WIDTH, SAPPHIRE_CELLS_HEIGHT),
  new Cell(220, 138, SAPPHIRE_CELLS_WIDTH, SAPPHIRE_CELLS_HEIGHT),
  new Cell(258, 138, SAPPHIRE_CELLS_WIDTH, SAPPHIRE_CELLS_HEIGHT),
  new Cell(294, 138, SAPPHIRE_CELLS_WIDTH, SAPPHIRE_CELLS_HEIGHT),
  new Cell(331, 138, SAPPHIRE_CELLS_WIDTH, SAPPHIRE_CELLS_HEIGHT),
];

export const SAPPHIRE_DATA: SpriteData[] = [
  new SpriteData(140, TRACK_BASELINES[1] - SAPPHIRE_CELLS_HEIGHT),
  new SpriteData(880, TRACK_BASELINES[2] - SAPPHIRE_CELLS_HEIGHT),
  new SpriteData(1100, TRACK_BASELINES[2] - SAPPHIRE_CELLS_HEIGHT),
  new SpriteData(1475, TRACK_BASELINES[1] - SAPPHIRE_CELLS_HEIGHT),
  new SpriteData(2400, TRACK_BASELINES[1] - SAPPHIRE_CELLS_HEIGHT),
];
